preset: recommended
risky: true
finder:
  exclude:
    - "modules"
    - "node_modules"
    - "storage"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"
    - index.php
    - server.php
