language: php

php:
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - docker-compose exec app php artisan migrate:fresh

script: vendor/bin/phpunit
